services:
# the first service
  proxy:
  # build from the Dockerfile in current directory
    build: . 
    # maps port 80 of the container to port 80 of the host
    ports:
      - "80:80" 
    # env vars needed
    environment:
    # because all the services are in the def together, we can access them by name, no need to specify ip
    # also can use same port for each backend as Docker auto differentiates them
      - UPSTREAM_ADDRS=backend-1:8848,backend-2:8849,backend-3:8850
      - HC_INTERVAL=15s
  
  # rest of the services
  backend-1:
  # build from the Dockerfile in testServer dir
    build: 
    # use ./ dir for the build so that it can find go.mod and go.sum
      context: .
      # use Dockerfile in ./cmd/testServer dir
      dockerfile: ./cmd/testServer/Dockerfile
    environment:
      - SERVER_NAME=backend-1
      - UPSTREAM_PORT=8848

  backend-2:
    build:
      context: .
      dockerfile: ./cmd/testServer/Dockerfile
    environment:
      - SERVER_NAME=backend-2
      - UPSTREAM_PORT=8849

  backend-3:
    build:
      context: .
      dockerfile: ./cmd/testServer/Dockerfile
    environment:
      - SERVER_NAME=backend-3
      - UPSTREAM_PORT=8850
      - DELAY_REQ=300ms

# to check if the least conn is working an idea is:
#  add a delay var to one of the backends
#  add the dealy to the backends endopoints
#  this will make that single backend slower and it should get fewer requests
#  will be slower cuz it will have to wait for the delay adn thus accumulate more active connections than the others
#  meaning the proxy will send less requests to the slower backend